### ISSUE TITLE
http://www.yafaray.org/ doesn't respond

### ISSUE THREAD

**Issue by yurivict** [YafaRay/libYafaRay#11] opened 2022-07-08 03:06 UTC

**Comment by DavidBluecame** [comment] 2022-07-10 10:23
Hello,

Thank you for reporting this problem. Unfortunately it's been happening for a long time.

For more details please check issue #2 

I'm closing this as a duplicate of #2  We can continue this discussion there.

Thanks again and best regards.

**Closed by DavidBluecame** 2022-07-10 10:23 UTC
